### ISSUE TITLE
Error when following User_Email example

### ISSUE THREAD

**Issue by dweirich** [swoosh/phoenix_swoosh#11]
Received this error when following Phoenix.Swoosh docs.

`(CompileError) web/emails/user_email.ex:6: Email.__struct__/1 is undefined, cannot expand struct Email`

Using this code

```
def welcome(user) do
    %Email{}
    |> from("user@example.com")
    |> to(user.email)
    |> subject("Welcome to Sample!")
    |> render_body("welcome.html", %{name: user.name})
  end
```

Was able to fix it by following Swoosh docs instead and replacing `%Email{}` with `new`.

**Comment by stevedomin** [comment]
Thanks for reporting @dweirich, it's fixed in https://github.com/swoosh/phoenix_swoosh/commit/238293f1d7749a4385485c711777ee072db687f4
