### ISSUE TITLE
Release a version based on phoenix 1.3.0-rc

### ISSUE THREAD

**Issue by smpallen99** [swoosh/phoenix_swoosh#12]
I'm trying to publish a package (coherence) that has this project as a dependency. The version I'm trying to publish has a dependency on phoenix-1.3.0-rc. I tried to publish my package with an override on phoenix, but hex won't allow that. 

Any chance you could publish a version with the updated phoenix dependency? Perhaps a rc version?

**Comment by smpallen99** [comment]
Don't need this. I'm going to downgrade my phoenix version.

**Comment by stevedomin** [comment]
@smpallen99 looks like you found a solution to your problem but let me know if I can help
