### ISSUE TITLE
Mismatch of File doc and Hexdoc

### ISSUE THREAD

**Issue by philippneugebauer** [swoosh/phoenix_swoosh#16]
There is a slight difference of the documentation between https://github.com/swoosh/phoenix_swoosh/blob/master/lib/phoenix_swoosh.ex and https://hexdocs.pm/phoenix_swoosh/Phoenix.Swoosh.html in the `Sample.UserEmail` module.
For the hexdoc, an added `alias Swoosh.Email` is required to compile the snippet succesfully, but which doc is the preferred one?

**Comment by stevedomin** [comment]
Hi @philippneugebauer,

Sorry about this, the code was updated but we didn't push the docs.

I'd recommend going with the `new/0` function, it is the preferred way to initialise a new Email struct.
