### ISSUE TITLE
A heads up: we have extract phoenix_view into a separate project

### ISSUE THREAD

**Issue by josevalim** [swoosh/phoenix_swoosh#194]
Hi everyone,

Thanks for the amazing lib!

Just a heads up, we have extract Phoenix.View into a separate library so it is easier for projects like Swoosh to add template rendering without depending on all of Phoenix: https://github.com/phoenixframework/phoenix_view

When Phoenix v1.6 comes out, you should be able to depend on `phoenix_view`. Although keep in mind that if someone is using `phoenix` v1.5 or earlier, then will run into issues. So you should probably either do a new major release or keep `{:phoenix, "~> 1.6", optional: true}` just as a check to avoid conflicts.

**Comment by princemaple** [comment]
Thanks José!

**Comment by princemaple** [comment]
Code is ready, in case you'd like to take a look.

I'll ask for feedback on the forum and make a release soon.
