### ISSUE TITLE
would it be possible to do another release ?

### ISSUE THREAD

**Issue by happysalada** [swoosh/phoenix_swoosh#205]
Since the last release uses html < 3.0.0, this is currently blocking upgrades to phoenix and live_view.

Would it be possible to do another release ?

Is there any way that I can help ?

**Comment by princemaple** [comment]
Released 0.3.4

**Comment by princemaple** [comment]
It was released from 0.3.x branch. The main branch is waiting on Phoenix 1.6. I'll release 1.0 as soon as Phoenix 1.6 is out.

**Comment by happysalada** [comment]
Thanks a lot!

**Comment by princemaple** [comment]
🙏
