### ISSUE TITLE
phoenix 1.6-rc0 - render_body with atom do nothing

### ISSUE THREAD

**Issue by romaluca** [swoosh/phoenix_swoosh#208]
Hi, i upgraded my webapp to phoenix 1.6-rc0 and now the tests of mail sending are failing
I noticed that the cause is render body with atom parameter (:registration_confirm) do nothing. No error is reported:

new()
    |> to({user.name, user.email})
    |> from(@from)
    |> subject(subject)
    |> render_body(:registration_confirm, %{username: user.name, url: url, subject: subject})

But if i change this in: 
new()
    |> to({user.name, user.email})
    |> from(@from)
    |> subject(subject)
    |> render_body("registration_confirm.html", %{username: user.name, url: url, subject: subject})

It works. In my app there are the "registration_confirm.html.eex" and "registration_confirm.text.eex"
Is not possible using atom any more?

**Comment by princemaple** [comment]
Hi, could you try 1.0.0-rc?

**Comment by princemaple** [comment]
There should be no breaking change and should work with phoenix 1.6

**Comment by romaluca** [comment]
I upgraded also phoenix_swoosh with:
{:phoenix_swoosh, git: "https://github.com/swoosh/phoenix_swoosh"},
but it the same.
The problem is that the render_body returns nothing and there is no logs.

**Comment by princemaple** [comment]
Hi @romaluca I'm going to need more info to debug that. Testing with a toy project shows that it works properly with atoms.

Could you setup a minimal reproducible example?

What I got:

> lib/test_swoosh/something.ex
```elixir
defmodule TestSwoosh.Something do
  use Phoenix.Swoosh, view: TestSwoosh.MyView

  def hi do
    new()
    |> subject("what")
    |> to("test@test.com")
    |> from("test@test.com")
    |> render_body(:hi, name: "world")
  end
end
```

> lib/test_swoosh/my_view.ex
```elixir
defmodule TestSwoosh.MyView do
  use Phoenix.View, root: "lib/test_swoosh/templates"
end
```

> lib/test_swoosh/templates/my/hi.html.eex
```html
<h1>Hello, <%= @name %></h1>
```

> lib/test_swoosh/templates/my/hi.text.eex
```
Hello, <%= @name %>
```

```elixir
iex(1)> TestSwoosh.Something.hi
%Swoosh.Email{
  assigns: %{layout: false, name: "world"},
  attachments: [],
  bcc: [],
  cc: [],
  from: {"", "test@test.com"},
  headers: %{},
  html_body: "<h1>Hello, world</h1>\n",
  private: %{
    phoenix_layout: false,
    phoenix_template: "hi.text",
    phoenix_view: TestSwoosh.MyView
  },
  provider_options: %{},
  reply_to: nil,
  subject: "what",
  text_body: "Hello, world\r\n",
  to: [{"", "test@test.com"}]
}
```

**Comment by princemaple** [comment]
`render_body` should always return the rendered email struct. There is not a case where it would return nothing.

**Comment by romaluca** [comment]
i found the cause is the layout. I have this:
`use Phoenix.Swoosh,
    view: ShuttertopWeb.UserMailerView,
    layout: {ShuttertopWeb.LayoutView, :email}`
and these files for the common layout:
```
lib/shuttertop_web/templates/layout/email.html.eex
lib/shuttertop_web/templates/layout/email.txt.eex
``'
If i remove this from the code it works:
`    layout: {ShuttertopWeb.LayoutView, :email}`
I tried also to change the content of the layout files with only:
`<%= render @view_module, @view_template, assigns %>`
or
`<%= @inner_content %>`
But it doesn't work.

**Comment by romaluca** [comment]
I tried the send with iex and there is an error:
`[error] %ArgumentError{message: "errors were found at the given arguments:\n\n  * 1st argument: not an iodata term\n"}`

**Comment by princemaple** [comment]
```
lib/shuttertop_web/templates/layout/email.txt.eex
```

Has this always been `txt`? Could you try `text`?

**Comment by princemaple** [comment]
I added layout and still works. I did get an error if I named it `email.txt.eex`, though.

> lib/test_swoosh/something.ex
```elixir
defmodule TestSwoosh.Something do
  use Phoenix.Swoosh, view: TestSwoosh.MyView, layout: {TestSwoosh.LayoutView, :email}

  def hi do
    new()
    |> subject("what")
    |> to("test@test.com")
    |> from("test@test.com")
    |> render_body(:hi, name: "world")
  end
end
```

> lib/test_swoosh/layout_view.ex
```elixir
defmodule TestSwoosh.LayoutView do
  use Phoenix.View, root: "lib/test_swoosh/templates"
end
```

> lib/test_swoosh/templates/layout/email.html.eex
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <%= @inner_content %>
  </body>
</html>
```

> lib/test_swoosh/templates/layout/email.text.eex
```
TEST <%= @inner_content %>
```

```elixir
iex(8)> TestSwoosh.Something.hi
%Swoosh.Email{
  assigns: %{layout: {TestSwoosh.LayoutView, "email.text"}, name: "world"},
  attachments: [],
  bcc: [],
  cc: [],
  from: {"", "test@test.com"},
  headers: %{},
  html_body: "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n    <title>Document</title>\n  </head>\n  <body>\n<h1>Hello, world</h1>\n\n  </body>\n</html>\n",
  private: %{
    phoenix_layout: {TestSwoosh.LayoutView, :email},
    phoenix_template: "hi.text",
    phoenix_view: TestSwoosh.MyView
  },
  provider_options: %{},
  reply_to: nil,
  subject: "what",
  text_body: "TEST Hello, world\r\n\n",
  to: [{"", "test@test.com"}]
}
```

**Comment by romaluca** [comment]
Excuse me, in my post i wanted write
`lib/shuttertop_web/templates/layout/email.text.eex`
Ok if it works to you, i'll check more my code.
Thanks anyway!

**Comment by princemaple** [comment]
Did you manage to figure out what the issue is?

**Comment by romaluca** [comment]
Yes, i used the same LayoutView for web pages and email
Before phoenix 1.6 it worked.
I created another LayoutView for email and now it works again.
Thanks

**Comment by princemaple** [comment]
Interesting. Thanks for the reply.
