### ISSUE TITLE
Upgrading to Swoosh 0.13

### ISSUE THREAD

**Issue by 51stpage** [swoosh/phoenix_swoosh#21]
It looks like Swoosh 0.1.0 is over two years old at this point.  Any reason not to upgrade to a more recent release?  I'm interested in getting access to the AmazonSES adapter found in a more recent version of Swoosh but definitely is not in 0.1.0.

**Comment by princemaple** [comment]
Hi @51stpage , `~> 0.1` pins the version to 0.x, which allows the latest version, `0.13.0`.

**Comment by 51stpage** [comment]
Ah, thank you.
