### ISSUE TITLE
How is the struct %Email{} available?

### ISSUE THREAD

**Issue by ndrean** [swoosh/phoenix_swoosh#261]
The example fails for me

```iex
defmodule Sample.UserEmail do
  use Phoenix.Swoosh, view: Sample.EmailView

  def welcome(user) do
    %Email{}   # <-- undefined
    |> from("tony@stark.com")
    |> to(user.email)
    |> subject("Hello, Avengers!")
    |> render_body("welcome.html", %{username: user.email})
  end
end
```

**Comment by princemaple** [comment]
Hi,

`use Phoenix.Swoosh, ...` imports `Swoosh.Email` but does not alias it.

You should either use `new()` instead of `%Email{}`

or

add `alias Swoosh.Email` below your `use`

or use `%Swoosh.Email{}` instead of `%Email{}`

**Comment by ndrean** [comment]
Ok, probably just slightly modify the doc!

**Comment by princemaple** [comment]
Thanks, will do
