### ISSUE TITLE
phoenix_html 4.0 compatibility

### ISSUE THREAD

**Issue by eKIK** [swoosh/phoenix_swoosh#349]
The current version of Swoosh (1.2.0)  depends on phoenix_html "~> 3.0". Since 4.0 is out now this has started causing some compatibility problems for me, as other libraries are moving to phoenix_html 4.0.

It'd be great to have phoenix_swoosh upgrade the phoenix_html dep to ~> 4.0. 
I'd be happy to give the upgrade a shot myself if that's OK?

**Comment by princemaple** [comment]
Hi, I've released v1.2.1 that allows `phoenix_html ~> 4.0`. Feel free to send PR to make additional changes that you see fit. Cheers!

**Comment by eKIK** [comment]
Thanks a bunch @princemaple for the super-quick fix! I just tried the new release and it works like a charm :)
