### ISSUE TITLE
render_body exception when using email as an assign.

### ISSUE THREAD

**Issue by ericsullivan** [swoosh/phoenix_swoosh#44]
I just ran into a previously closed issue: https://github.com/swoosh/swoosh/issues/152

The exception was "protocol Phoenix.HTML.Safe not implemented for %Swoosh.Email", and the solution mentioned was:

```elixir
|> render_body("welcome.html", %{email: user.email}) # <--- don't do this
```

What do you think about raising an exception "don't use email for assigns". I think the place to put it is right before here: https://github.com/swoosh/phoenix_swoosh/blob/master/lib/phoenix_swoosh.ex#L159

```elixir
content = Phoenix.View.render_to_string(view, template, Map.put(email.assigns, :email, email))
```

I can submit a PR if the approach seems fine.

**Comment by princemaple** [comment]
I think it's a reasonable approach. Please also note something like "the :email assign is used by Swoosh  and will be overwritten".
