### ISSUE TITLE
Why does it need to be in application

### ISSUE THREAD

**Issue by olafura** [swoosh/phoenix_swoosh#6]
Hi, I don't understand why you need to add :phoenix_swoosh into applications it does not have a start function.

**Comment by stevedomin** [comment]
Hi @olafura, you need to do it so that the applications `phoenix_swoosh` depends on are started as well.

Also this makes sure the application is added to Elixir releases. There was a really good post on the mailing list about that, trying to find it now.

**Comment by stevedomin** [comment]
As of Elixir 1.4 we don't need to add it to the applications list, will update the README.md
